
services:
  api:
    image: ghcr.io/eleusiscarretero/input_data_test_cases/input_data_test_cases:latest
    environment:
      DB_HOST: ${DB_HOST:?DB_HOST missing}
      DB_USER: ${DB_USER:?DB_USER missing}
      DB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD missing}
      DB_PORT: ${DB_PORT:?DB_PORT missing}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 15s
      timeout: 3s
      retries: 5
