name: Testing

on:
  workflow_call:
    inputs:
      file_under_test:
        type: string
        default: '.'
      python-version:
        type: string
        default: '3.11'
 
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-common-env
        with:
          python-version: '3.11'
          env: 'test'

      - name: ⚒️ Execute Unit Testing
        shell: bash
        run: |
          pwd
          set +e
          python -m unittest discover -s test/unit_tests -p "test_*.py" -v > result.log 2>&1
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "TEST_RESULT=✅ Tests passed" >> $GITHUB_ENV
          else
            echo "TEST_RESULT=❌ Tests failed" >> $GITHUB_ENV
          fi
          cat result.log

  functional-test:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-common-env
        with:
          python-version: '3.11'
          env: 'test'
        
      - name: ⚒️ Execute Functional Testing
        shell: bash
        run: |
          behave test\\functional_tests\\features -n Add a new test case and delete it
